### ISSUE TITLE
FeatureWriter outputs illegal class names

### ISSUE THREAD

**Issue by adrientetar** [jamesgk/ufo2ft#10]
e.g. I have a generated featurefile like this:

```
@MMK_R_FF000000000000020 = [A J];
public.kern2.@MMK_R_FF000000000000011 = [b h k l Thorn thorn];
```

- In FEA, named glyph classes must start with @, which isn't currently enforced.
- Also, class names must follow the same naming restrictions as glyph names (`A-Z a-z 0-9 . (period) _ (underscore)`), we let the user write correct data for the featurefile in the UFO but the FeatureWriter shouldn't output incorrect FEA code (UFO itself puts no name restrictions on groups names, except UFO3 which specificies kerning groups should begin with `public.kernX`)

(Lastly after the normalization pass we should make sure that no duplicate class names were produced, e.g. `group` and `group#` may yield the same name after normalization.)

**Comment by jamesgk** [comment]
Should be fixed by #12
