### ISSUE TITLE
fork ufo2fdk?

### ISSUE THREAD

**Issue by anthrotype** [jamesgk/ufo2ft#4]
Currently ufo2ft shows up in github as "forked" from typesupply/ufo2fdk.
However, given the drastic changes to the api, I don't think the intention is to fold ufo2ft back in ufo2fdk repo.

If that is the case, then @jamesgk could delete the current ufo2ft repo, create a new Github repo called again "ufo2ft" and push his local copy to the new remote.

This way, Github will see it as an independent repository, instead of a fork of someone else's repo. The commit history will be kept intact however. 

This would allow others to fork directly from James' "ufo2ft". At the moment, in fact, if one tries to fork from ufo2ft, Github will not allow it if the user has already forked ufo2fdk.

I had to resort to special "ufo2ft-*" branch names on my "hybrid" anthrotype/ufo2fdk fork, in order to be able to track both typesupply/ufo2fdk and jamesgk/ufo2ft...

**Comment by adrientetar** [comment]
You can also ask support to switch the repository to a distinct one.

**Comment by davelab6** [comment]
You can unlink the repos without deleting anything. Just email
support@github.com

**Comment by anthrotype** [comment]
well, even better then. Whatever works for you.

**Comment by jamesgk** [comment]
OK, ufo2ft has been extracted from ufo2fdk. This means that we adopted ufo2fdk's ufo3 branch, which frankly I want to get rid of asap. I don't want to worry about maintaining two separate branches -- for now I just want to incorporate ufo3 support as long as it's compatible with ufo2.

**Comment by adrientetar** [comment]
As I told you before, the difference is mainly kerning prefixes. The ufo3 branch of ufo2fdk also drops heuristic to extract kerning groups from any group since in ufo3 kerning groups have a well-defined prefix. 
I don't think that there is much difference besides that.

**Comment by jamesgk** [comment]
ufo2ft is now distinct, and the ufo3 branch is deleted. I'm gonna close this.
